---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orgchart
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgchart
  labels:
    app: orgchart
spec:
  selector:
    matchLabels:
      app: orgchart
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'orgchart'
        vault.hashicorp.com/agent-inject-secret-database-config.txt: 'orgchart/data/database/config'
        vault.hashicorp.com/agent-inject-secret-env: 'orgchart/data/database/config'
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "orgchart/data/database/config" -}}
          export DB_USERNAME={{ .Data.data.username }}
          export DB_PASSWORD={{ .Data.data.password }}
          {{- end }}
      labels:
        app: orgchart
    spec:
      serviceAccountName: orgchart
      containers:
        - name: orgchart
          image: jweissig/app:0.0.1
